# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: GriSPy

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        py_version: [3.8]
        tox_env:
          - style
          - docstyle
          - check-manifest
          - coverage
          - make-docs
        include:
          - py_version: 3.7
            tox_env: py37
          - py_version: 3.8
            tox_env: py38
          - py_version: 3.9
            tox_env: py39
            
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pandoc
        if: ${{ matrix.tox_env == 'make-docs'}}
        run: sudo apt-get install pandoc
      - name: Install tox
        run: pip install tox
      - name: Test with tox
        run: tox -r

      - name: Export coverage
        if: ${{ matrix.python-version == '3.8' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        run: |
          pip install coveralls
          coveralls --service=github             
