# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: GriSPy CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py_version: [3.9]
        tox_env:
          - style
          - docstyle
          - check-manifest
          - coverage
          - make-docs
        include:
          - py_version: 3.6
            tox_env: py36
          - py_version: 3.7
            tox_env: py37
          - py_version: 3.8
            tox_env: py38
          - py_version: 3.9
            tox_env: py39

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py_version }}

      - name: Install pandoc
        if: ${{ matrix.tox_env == 'make-docs'}}
        run: sudo apt-get install pandoc

      - name: Install tox
        run: pip install tox
      - name: tox -e ${{ matrix.tox_env }}
        run: tox -re ${{ matrix.tox_env }}

      - name: Export coverage
        if: ${{ matrix.tox_env == 'coverage' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install coveralls
          coveralls --service=github
