# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: GriSPy

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: Install pandoc
        run: sudo apt-get install pandoc
      - name: Install tox
        run: pip install tox tox-gh-actions coveralls
      - name: Test with tox
        run: tox -r
      - name: Test Coverage          
        if: ${{ matrix.python-version == '3.8' && env.TOXENV == 'coverage'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        run: coveralls --service=github             
